---
- name: Copy file remote server
  hosts: web_update

  vars:
    source_file: /Ansible/test.txt
    destin_file: /tmp

  tasks:
  - name: Copy file
    copy: src={{source_file}}  dest={{destin_file}} mode=0550